### PR TITLE
Enable create.boxplot to print different text label on each panel

### PR DESCRIPTION
**Pull request by zhuchcn**
This is an work around to be able to set different text labels on each panel

Data: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/files/7003378/create.boxplot.data.txt

```R
data <- read.table(file = 'create.boxplot.data.txt', header = TRUE);
dummy.data <- data.frame(
    expression_score = NA,
    sex = 'Male',
    gene = 'DDX3X'
    );
data <- rbind(data, dummy.data);
data <- data[order(data$gene, data$sex),]

# Assemble color vector
sex.colours <- replace(data$sex, which(data$sex == 'Male'),'dodgerblue');
sex.colours <- replace(sex.colours, which(data$sex == 'Female'), 'pink');
# Plot
ymin <- min(data$expression_score, na.rm = TRUE)
ymax <- max(data$expression_score, na.rm = TRUE)
ymax <- ymax + (ymax - ymin) * 0.15
p <- create.boxplot(
    formula = expression_score ~ sex | gene,
    data = data,
    add.stripplot = TRUE,
    points.col = sex.colours,
    text.labels = c('A', 'B'),
    text.x = 1.5,
    text.y = 0,
    add.text = TRUE,
    ylimits = c(ymin, ymax)
    );
```

image

### CODE REVIEW

**Review by pboutros — COMMENTED** [review]
Was assigned to @dan-knight, please coordinate with him

Also, not in coding standard, please fix

**Comment by zhuchcn** [comment]
@pboutros  Just fixed the styling. 

@dan-knight This does not fix #4 , but only enable setting text labels on each panel. But i think the color can be handled in a similar manner.

**Comment by zhuchcn** [comment]
@dan-knight I added some text in documentation. 

The repo do not have branch protection currently. I think we should add it.

**Comment by dan-knight** [comment]
> @dan-knight I added some text in documentation.
> 
> The repo does not have branch protection currently. I think we should add it. But for best practice, can you approve it when you feel it is ready? @dan-knight

Definitely agree about the branch protection.

I tested the new labels and everything looks good to me. I'll merge this branch now, and then test the stripplot colour fix with this feature included.

**Pull request merged**
