### PR TITLE
Update citation information to match `citation('Boutros.plotting.general')`

### PR DESCRIPTION
**Pull request by forbiddenpersimmon**
# Description
Update citation information to match `citation('Boutros.plotting.general')` to keep consistent with changes suggested to VennDiagram README

# Checklist

- [x] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data.  A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
- [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files.  To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example.
- [X] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).
- [X] I have set up or verified the `main` branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.
- [X] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].
- [ ] I have added the major changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

### CODE REVIEW

**Comment by stefaneng** [comment]
@forbiddenpersimmon The `citation('Boutros.plotting.general')` is actually not correct. There is an issue open here: https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/issues/80 to add the CITATION file.

It should reference the paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2610-2 rather than the package directly. The VennDiagram CITATION file is a good reference: https://github.com/uclahs-cds/public-R-VennDiagram/blob/main/inst/CITATION

**Comment by forbiddenpersimmon** [comment]
> @forbiddenpersimmon The `citation('Boutros.plotting.general')` is actually not correct. There is an issue open here: #80 to add the CITATION file.
> 
> It should reference the paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2610-2 rather than the package directly. The VennDiagram CITATION file is a good reference: https://github.com/uclahs-cds/public-R-VennDiagram/blob/main/inst/CITATION

I've used the VennDiagram reference as a guide but am stumped by the author entry. The BPG paper has many listed authors and not sure up to who should be written out before "et. al." Also would you know if all authors are separated by "and" or just commas? Have seen differing answers when I looked it up.

**Comment by stefaneng** [comment]
> > @forbiddenpersimmon The `citation('Boutros.plotting.general')` is actually not correct. There is an issue open here: #80 to add the CITATION file.
> > It should reference the paper: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2610-2 rather than the package directly. The VennDiagram CITATION file is a good reference: https://github.com/uclahs-cds/public-R-VennDiagram/blob/main/inst/CITATION
> 
> @stefaneng I've used the VennDiagram reference as a guide but am stumped by the author entry. The BPG paper has many listed authors and not sure up to who should be written out before "et. al." Also would you know if all authors are separated by "and" or just commas? Have seen differing answers when I looked it up.

Here is what I think the corresponding bibtex file should look like:

```
@article{Png2019,
  doi = {10.1186/s12859-019-2610-2},
  url = {https://doi.org/10.1186/s12859-019-2610-2},
  year = {2019},
  month = jan,
  publisher = {Springer Science and Business Media {LLC}},
  volume = {20},
  number = {42},
  author = {Christine P'ng and Jeffrey Green and Lauren C. Chong and Daryl Waggott and Stephenie D. Prokopec and Mehrdad Shamsi and Francis Nguyen and Denise Y. F. Mak and Felix Lam and Marco A. Albuquerque and Ying Wu and Esther H. Jung and Maud H. W. Starmans and Michelle A. Chan-Seng-Yue and Cindy Q. Yao and Bianca Liang and Emilie Lalonde and Syed Haider and Nicole A. Simone and Dorota Sendorek and Kenneth C. Chu and Nathalie C. Moon and Natalie S. Fox and Michal R. Grzadkowski and Nicholas J. Harding and Clement Fung and Amanda R. Murdoch and Kathleen E. Houlahan and Jianxin Wang and David R. Garcia and Richard de Borja and Ren X. Sun and Xihui Lin and Gregory M. Chen and Aileen Lu and Yu-Jia Shiah and Amin Zia and Ryan Kearns and Paul C. Boutros},
  title = {{BPG}: Seamless,  automated and interactive visualization of scientific data},
  journal = {{BMC} Bioinformatics}
}
```

From there is is realtively straightforward to convert to R's bibentry format.


I used doi2bib and edited a few entries: https://www.doi2bib.org/bib/https://doi.org/10.1186/s12859-019-2610-2

**Review by stefaneng — APPROVED** [review]
Looks great!

**Pull request merged**
