### PR TITLE
Use pkgdown for BPG documentation

### PR DESCRIPTION
**Pull request by stefaneng**
There has been some discussion about a lack of package documentation for the newer version of BPG. (See: https://github.com/uclahs-cds/bl-manual/pull/20 for example). Most people in the lab still use: https://development.boutroslab.net/API/BoutrosLab.plotting.general/5.9.2/ but using pkgdown will allow us to keep it up to date with current version on github. 

Currently am hosting on an F2 node here: http://10.18.82.49:8000/ to check out how it looks.

Changes in this PR:
  - Comment out filename in example so that pkgdown will generate the plots
  - Setup github actions to push to gh-pages (need to enable github pages on the repo)

Some things I think we want to update as well that I noticed while generating the docs:
  - We need a README
  - Update citation information to P’ng et al.

### CODE REVIEW

**Comment by tyamaguchi-ucla** [comment]
@stefaneng @dan-knight would it be possible to fix the R-CMD-check issues?

**Comment by stefaneng** [comment]
@tyamaguchi-ucla I found the issue. The failing cases were those that had `use.legacy.settings = TRUE` or `style = 'Nature'`. I don't know the history behind the function: [get.defaults](https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/6e861c2c61d4fa72f62a493f9aa236f65c65e2b2/R/get.defaults.R#L17-L25) but it doesn't seem to influence the output of the plot font except it fails when using the default grid graphics device on linux machine. I just commented those lines out but the entire function really doesn't do anything at this point.

On a different note, the docs look good now at: http://10.18.82.49:8000 I could push these pkgdown docs to the gh-pages branch so we at least have the up-to-date documentation somewhere for now.

**Review by tyamaguchi-ucla — DISMISSED** [review]
>@tyamaguchi-ucla I found the issue. The failing cases were those that had use.legacy.settings = TRUE or style = 'Nature'. I don't know the history behind the function: [get.defaults](https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/6e861c2c61d4fa72f62a493f9aa236f65c65e2b2/R/get.defaults.R#L17-L25) but it doesn't seem to influence the output of the plot font except it fails when using the default grid graphics device on linux machine. I just commented those lines out but the entire function really doesn't do anything at this point.

I'm not familiar with the history, either. Maybe it makes sense to revisit the feature to enable various styles in the future but I don't think it's urgent at all.

>On a different note, the docs look good now at: http://10.18.82.49:8000/ I could push these pkgdown docs to the gh-pages branch so we at least have the up-to-date documentation somewhere for now.

We haven't really tried the gh-pages before but I think that'll sort of solve #37 as the repo is already public.

**Comment by stefaneng** [comment]
> > @tyamaguchi-ucla I found the issue. The failing cases were those that had use.legacy.settings = TRUE or style = 'Nature'. I don't know the history behind the function: [get.defaults](https://github.com/uclahs-cds/public-R-BoutrosLab-plotting-general/blob/6e861c2c61d4fa72f62a493f9aa236f65c65e2b2/R/get.defaults.R#L17-L25) but it doesn't seem to influence the output of the plot font except it fails when using the default grid graphics device on linux machine. I just commented those lines out but the entire function really doesn't do anything at this point.
> 
> I'm not familiar with the history, either. Maybe it makes sense to revisit the feature to enable various styles in the future but I don't think it's urgent at all.
> 
> > On a different note, the docs look good now at: http://10.18.82.49:8000/ I could push these pkgdown docs to the gh-pages branch so we at least have the up-to-date documentation somewhere for now.
> 
> We haven't really tried the gh-pages before but I think that'll sort of solve #37 as the repo is already public.

This will solve #37 as well.

Could you approve again since I removed the extra .gitignore file?

**Review by tyamaguchi-ucla — DISMISSED** [review]
>Could you approve again since I removed the extra .gitignore file?

Sure. It looks like this repo requires approval from the code-owner (Dan) though.

**Comment by stefaneng** [comment]
@dan-knight @tyamaguchi-ucla gh-pages is now live: https://uclahs-cds.github.io/public-R-BoutrosLab-plotting-general/

I used git lfs for the images since there was about 100mb of plots to push. Thoughts on enabling git lfs on all images?

**Review by dan-knight — APPROVED** [review]
Approving this. I'd say it's about 95% of the way there. There are a couple plotting specific (maybe BPG specific) bugs that don't have obvious solutions. These should probably be resolved in separate PRs. Even with the minor plotting issues, this is still a major improvement.

**Pull request merged**
