### PR TITLE
Fix ylab.axis.padding parameter in create.histogram

### LINKED ISSUE #71: ylab.axis.padding does nothing in create.histogram
The parameter `ylab.axis.padding` does not change the y-label axis padding. See the example of behavior in `create.scatterplot` vs `create.histogram`

``` r
library(BoutrosLab.plotting.general, quietly = T, warn.conflicts = F)
set.seed(10)
x <- data.frame(x = rnorm(100), y = rnorm(100))
create.scatterplot(
    y ~ x,
    data = x,
    ylab.label = 'ylab',
    ylab.axis.padding = 15
    )
```

``` r

create.histogram(
    x$y,
    ylab.label = 'ylab',
    ylab.axis.padding = 15
    )
```

<sup>Created on 2023-01-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by stefaneng**
# Description

Fix `create.histogram` to use `ylab.axis.padding` parameter.

### Closes #71 

# Checklist

- [x] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data.  A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
- [x] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files.  To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example.
- [x] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).
- [x] I have set up or verified the `main` branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.
- [x] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].
- [x] I have added the major changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

## Example
```r
set.seed(10)
x <- rnorm(100)
create.histogram(
    x,
    ylab.label = 'ylab',
    ylab.axis.padding = 15
    )
```

image

### CODE REVIEW

**Review by aholmes — APPROVED** [review]

**Comment by stefaneng** [comment]
@dan-knight 7.0.5 is not released yet right? I didn't update the version for this patch.

**Comment by dan-knight** [comment]
> @dan-knight 7.0.5 is not released yet right? I didn't update the version for this patch.

Ah, I already submitted it (waiting on CRAN approval). This should be v7.0.6

**Comment by pboutros** [comment]
Should I reject @ CRAN or approve?

**Comment by stefaneng** [comment]
@pboutros @dan-knight I'm fine with this being in 7.0.6 so no need to reject CRAN. I'll update the version for this PR.

**Review by dan-knight — APPROVED** [review]
LGTM!

**Pull request merged**
